apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: fluxmeter
  labels:
    app.kubernetes.io/part-of: fluxmeter
    app.kubernetes.io/component: redis
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
