apiVersion: v1
kind: Service
metadata:
  name: kafka-brokers
  namespace: fluxmeter
  labels:
    app.kubernetes.io/part-of: fluxmeter
    app.kubernetes.io/component: kafka
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9092
      targetPort: internal
    - name: controller
      port: 9093
      targetPort: controller
