apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: fluxmeter
  labels:
    app.kubernetes.io/part-of: fluxmeter
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: native
      port: 9000
      targetPort: native
    - name: metrics
      port: 9363
      targetPort: metrics
