apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: fluxmeter
  labels:
    app.kubernetes.io/part-of: fluxmeter
    app.kubernetes.io/component: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluxmeter-prometheus
  labels:
    app.kubernetes.io/part-of: fluxmeter
    app.kubernetes.io/component: observability
rules:
  - apiGroups: [""]
    resources: [nodes, nodes/metrics, services, endpoints, pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get]
  - nonResourceURLs: ["/metrics"]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluxmeter-prometheus
  labels:
    app.kubernetes.io/part-of: fluxmeter
    app.kubernetes.io/component: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluxmeter-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: fluxmeter
